[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "nextflow-runner-service"
version = "1.6.0"
description = "Service producing and displaying sequencing reports."
readme = "README.md"
requires-python = ">=3.10"
keywords = ["bioinformatics"]
authors =[
    {name = 'SNP&SEQ Technology Platform, Uppsala University'}
]
dependencies = [
    "alembic",
    "arteria==1.1.4",
    "jsonschema",
    "sqlalchemy<2",
    "tornado",
]

[dependency-groups]
dev = [
    "bumpversion",
    "coverage",
    "flake8",
    "mock",
    "pytest",
    "pytest-asyncio",
    "pytest-runner",
    "sphinx",
    "twine",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["nextflow_runner_service*"]

[project.scripts]
nextflow-runner-service  = "nextflow_runner_service.app:start"
